import gql from "graphql-tag";

const GET_ADMINE=gql`
  query{
    searchAll{
      id,
      userName,
      email,
      firstname,
      lastName,
      roles
    }
  }
`
const GET_USERNAME=gql`
  query{
    getUserName
  }
`
const GET_EXERCICES=gql`
  query{
    exerciceList{
      id
      date_debut
      date_fin
      saisieJournauxes{
        intitule_journale
        exercice{
          id
        }
      }
      societe{
        id
        compteUtilisateur{
          id
          email
          bureau{
            adresse

          }
        }
      }
    }
  }
`
const MESSAGES_CHAT=gql`
  query($senderId:String,$recipientId:String){
    findChatMessages(senderId:$senderId,recipientId:$recipientId){
      id
      chatId
      recipientId
      senderId
      content
      senderName
      recipientName
      timestamp
      status
    }
  }
`

const GET_BUREAUX=gql`
  query($id:String){
    bureauListByAdminId(id:$id){
      id
      nom
      adresse
      ville
      paye
      numero_tele
      email
      admine{
        id
        nom
        prenom
        email
      }
    }
  }
`

const GET_BUREAU_BY_ID=gql`
  query($id:String){
    bureauById(id:$id){
      id
      nom
      adresse
      ville
      paye
      numero_tele
      email
      admine{
        id
        nom
        prenom
        email
      }
    }
  }
`
const COUNT_NEW_MESSAGES=gql`
  query($senderId:String,$recipientId:String){
    countNewMessages(senderId:$senderId,recipientId:$recipientId)

  }
`

const GET_COMPTE_UTILISATEUR=gql`
  query($idBureau:String){
    compteUtilisateurListByBureauId(idBureau:$idBureau){
      id
      nom
      prenom
      email
      adresse
      ville
      pays
      telephone
      date_naissance
      actif
      bureau{
        id
        nom
        adresse
      }
    }
  }
`

const GET_SOCIETE=gql`
  query($idUtilisateur:String){
    societeByIdUtilisateur(idUtilisateur:$idUtilisateur){
      id
      raison_social
      activite
      adresse
      compteUtilisateur{
        id
        nom
        prenom
      }
      ville
      pays
      devise
      forme_juridique
      capital
      telephone
      email
      site_internet
      num_dossier
      identifiant_TVA
    }
  }
`

const GET_SOCIETE_BY_ID=gql`
  query($idSociete:String){
    societeById(id:$idSociete){
      id
      raison_social
      activite
      adresse
      compteUtilisateur{
        id
        nom
        prenom
      }
      ville
      pays
      devise
      forme_juridique
      capital
      telephone
      email
      site_internet
      num_dossier
      identifiant_TVA
    }
  }
`

const GET_SOCIETE_MEMBERS=gql`
  query($id:String){
    membersList(id:$id){
      id
      societe{
        id
        raison_social
      }
      createur{
        id
        nom
        prenom
        email
      }
      member{
        id
        nom
        prenom
        email
      }
    }
  }
`

const GET_SOCIETE_SHARED=gql`
  query($id:String){
    membersListByMemberId(id:$id){
      id
      societe{
        id
        raison_social
        activite
        adresse
        ville
        identifiant_TVA
        pays
        compteUtilisateur{
          id
          prenom
          nom
        }
        devise
        forme_juridique
        capital
        telephone
        email
        site_internet
        num_dossier

      }
      createur{
        id
        nom
        prenom
      }
      member{
        id
        nom
        prenom
      }
    }
  }
`

const GET_COMPTES_GENERAUX_SOCIETE=gql`
  query($id:String){
    compteGeneralByIdSociete(id:$id){
      id
      idSociete
      natureCompte
      debutFaurchette
      finFaurchette
    }
  }
`
const GET_COMPTE_GENERAL_BY_ID=gql`
  query($id:String){
    compteGeneralById(id:$id){
      id
      natureCompte
      debutFaurchette
      finFaurchette
      idSociete
    }
  }
`
const GET_PLAN_COMPTABLE=gql`
  query($id:String){
    planComptableElementBySocieteId(id:$id){
      id
      numeroCompte
      intitule
      reporter
      societeId
      compteGeneral{
        id
        natureCompte
        debutFaurchette
        finFaurchette
      }
    }
  }
`
const GET_PLAN_COMPTABLE_BY_ID=gql`
  query($id:String){
    planComptableElementById(id:$id){
      id
      numeroCompte
      intitule
      reporter
      compteGeneral{
        id
        natureCompte
        debutFaurchette
        finFaurchette
        idSociete
      }
      societeId
    }
  }
`
const GET_AGENCE_BY_ID_SOCIETE=gql`
  query($id:String){
    agenceByIdSociete(id:$id){
      id
      nom
      complement
      code_postale
      ville
      pays
      societeId
    }
  }
`
const GET_AGENCE_ID=gql`
  query($id:String){
    agenceById(id:$id){
      id
      nom
      complement
      code_postale
      ville
      pays
      societeId
    }
  }
`
const GET_BANQUE_BY_AGENCE_ID=gql`
  query($id:String){
    banqueByIdAgence(id:$id){
      id
      abrege
      intitule
      interlocuteur
      codeBIC
      adresse
      code_postale
      ville
      pays
      telephone
      telecopie
      email
      site_internet
    }
  }
`
const GET_BANQUE_ID=gql`
  query($id:String){
    banqueById(id:$id){
      id
      abrege
      intitule
      interlocuteur
      codeBIC
      adresse
      code_postale
      ville
      pays
      telephone
      telecopie
      email
      site_internet
    }
  }
`

const GET_COMPTE_BANCAIRE_By_BANQUE=gql`
  query($id:String){
    compteBancaireListByBanqueId(id:$id){
      id
      abrege
      devise
      pays
      structure
      num_compte
      num_guichet
      planComptableElement{
        id
        intitule
        numeroCompte
      }
      planComptableElementId
      banque{
        id
        abrege
      }
    }
  }
`
const GET_COMPTE_BANCAIRE_By_ID=gql`
  query($id:String){
    compteBancaireById(id:$id){
      id
      abrege
      devise
      pays
      structure
      num_compte
      num_guichet
      planComptableElement{
        id
        numeroCompte
        intitule
      }
      planComptableElementId
      banque{
        id
        abrege
      }
    }
  }
`

const GET_CONTACT_BY_BANQUE=gql`
  query($id:String){
    contactByIdBanque(id:$id){
      id
      type_contact
      civilite
      nom
      prenom
      service
      fonction
      telephone
      portable
      email
      telecopie
      banque{
        id
      }
    }
  }
`
const GET_CONTACT_BY_ID=gql`
  query($id:String){
    contactById(id:$id){
      id
      type_contact
      civilite
      nom
      prenom
      service
      fonction
      telephone
      portable
      email
      telecopie
      banque{
        id
      }
    }
  }
`

const GET_CLIENT_BY_IDSOCIETE=gql`
  query($id:String){
    clientListByIdSociete(idSociete:$id){
      id
      nom
      prenom
      email
      adresse
      ville
      pays
      telephone
      societeId
      planComptableElementId
      planComptableElement{
        id
        numeroCompte
        intitule
        compteGeneral{
          id
          natureCompte
          debutFaurchette
          finFaurchette
        }
      }
    }
  }
`

const GET_CLIENT_BY_ID=gql`
  query($id:String){
    clientById(id:$id){
      id
      nom
      prenom
      email
      adresse
      ville
      pays
      telephone
      societeId
      planComptableElementId
      planComptableElement{
        id
        numeroCompte
        intitule
        compteGeneral{
          id
          natureCompte
          debutFaurchette
          finFaurchette
        }
      }
    }
  }
`
const GET_FOURNISSEUR_BY_ID_SOCIETE=gql`
  query($id:String){
    fournisseurByIdSociete(idSociete:$id){
      id
      nom
      prenom
      email
      adresse
      ville
      pays
      telephone
      societeId
      planComptableElementId
      planComptableElement{
        id
        numeroCompte
        intitule
        compteGeneral{
          id
          natureCompte
          debutFaurchette
          finFaurchette
        }
      }
    }
  }
`
const GET_FOURNISSEUR_BY_ID=gql`
  query($id:String){
    fournisseurById(id:$id){
      id
      nom
      prenom
      email
      adresse
      ville
      pays
      telephone
      societeId
      planComptableElementId
      planComptableElement{
        id
        numeroCompte
        intitule
        compteGeneral{
          id
          natureCompte
          debutFaurchette
          finFaurchette
        }
      }
    }
  }
`

const GET_SALARIEE_BY_ID_SOCIETE=gql`
  query($id:String){
    salarieeByIdSociete(idSociete:$id){
      id
      nom
      prenom
      email
      adresse
      ville
      pays
      telephone
      societeId
      planComptableElementId
      planComptableElement{
        id
        numeroCompte
        intitule
        compteGeneral{
          id
          natureCompte
          debutFaurchette
          finFaurchette
        }
      }
    }
  }
`
const GET_SALARIEE_BY_ID=gql`
  query($id:String){
    salarieeById(id:$id){
      id
      nom
      prenom
      email
      adresse
      ville
      pays
      telephone
      societeId
      planComptableElementId
      planComptableElement{
        id
        numeroCompte
        intitule
        compteGeneral{
          id
          natureCompte
          debutFaurchette
          finFaurchette
        }
      }
    }
  }
`


const GET_EXERCICE_BY_ID_SOCIETE=gql`
  query($id:String){
    fullExerciceListBySocieteId(id:$id){
      id
      date_debut
      date_fin
      societeId
    }
  }
`

const GET_EXERCICE_BY_ID=gql`
  query($id:String){
    exerciceById(id:$id){
      id
      date_debut
      date_fin
      societeId
    }
  }
`

const GET_CODE_JOURNAUX_BY_EXERCICE=gql`
  query($id:String){
    fullCodeJournalListByExerciceId(id:$id){
      id
      code
      intitule_journale
      type_journal
      exercice{
        id
        date_debut
        date_fin
        societeId
      }
    }
  }
`

const GET_CODE_JOURNAUX_BY_ID=gql`
  query($id:String){
    codeJournalById(id:$id){
      id
      code
      intitule_journale
      type_journal
      exercice{
        id
        date_debut
        date_fin
        societeId
      }
    }
  }
`

const GET_SAISIE_JOURNAL_BY_EXERCICE=gql`
  query($idExercice:String){
    saisieJournauxByExercice(idExercice:$idExercice){
      id
      position
      periode
      code
      intitule_journale
      classement
      code_Journal{
        id
        code
        type_journal
        exercice{
          id
        }
      }
    }
  }
`

const GET_SAISIE_JOURNAL_BY_ID=gql`
  query($id:String){
    saisieJournalById(id:$id){
      id
      position
      periode
      code
      intitule_journale
      classement
      code_Journal{
        id
        code
        type_journal
        exercice{
          id
        }
      }
    }
  }
`

const GET_JOURNAL_BY_SAISI_JOURNAL=gql`
  query($id:String){
    journaleBySaisieJournal(id:$id){
      id
      jour
      numFacture
      ref
      numCompteId
      numCompteTiereId
      libelle
      credit
      debit
      numCompte{
        id
        numeroCompte
        intitule
      }
      numCompteTiere{
        id
        numeroCompte
        intitule
      }
      saisieJournaux{
        id
        position
        periode
        intitule_journale
      }
    }
  }
`
const GET_JOURNAL_BY_ID=gql`
  query($id:String){
    journaleById(id:$id){
      id
      jour
      numFacture
      ref
      numCompteId
      numCompteTiereId
      libelle
      credit
      debit
      numCompte{
        id
        numeroCompte
        intitule
      }
      numCompteTiere{
        id
        numeroCompte
        intitule
      }
      saisieJournaux{
        id
        position
        periode
        intitule_journale
      }
    }
  }
`

const GET_EXERCICE_ETAT=gql`
  query{
    exerciceEtatList{
      id
      isFermer
      classement
      resultat
      exerciceId
    }
  }
`
const GET_EXERCICE_ETAT_BY_ID_EXERCICE=gql`
  query($id:String){
    findByIdExercice(id:$id){
      id
      isFermer
      classement
      resultat
      exerciceId
    }
  }
`
const IS_ALL_EXERCICE_OF_SOCIETE_CLOSE=gql`
  query($id:String){
    idAllExerciceCloseOfSociete(idSociete:$id)
  }
`
const GET_LAST_RESULTAT=gql`
  query($id:String){
    getLastResultat(idSociete:$id){
      id
      isFermer
      classement
      resultat
      exerciceId
    }
  }
`
export {GET_ADMINE,GET_EXERCICES,GET_USERNAME,MESSAGES_CHAT,COUNT_NEW_MESSAGES,GET_BUREAUX,
  GET_BUREAU_BY_ID,GET_COMPTE_UTILISATEUR,GET_SOCIETE,GET_SOCIETE_BY_ID,GET_SOCIETE_MEMBERS,
  GET_SOCIETE_SHARED,GET_COMPTES_GENERAUX_SOCIETE,GET_COMPTE_GENERAL_BY_ID,GET_PLAN_COMPTABLE,
  GET_PLAN_COMPTABLE_BY_ID,GET_AGENCE_BY_ID_SOCIETE,GET_AGENCE_ID,GET_BANQUE_BY_AGENCE_ID,GET_BANQUE_ID,
  GET_COMPTE_BANCAIRE_By_BANQUE,GET_COMPTE_BANCAIRE_By_ID,GET_CONTACT_BY_ID,GET_CONTACT_BY_BANQUE,
  GET_CLIENT_BY_IDSOCIETE,GET_CLIENT_BY_ID,GET_FOURNISSEUR_BY_ID_SOCIETE,GET_FOURNISSEUR_BY_ID,
  GET_SALARIEE_BY_ID_SOCIETE,GET_SALARIEE_BY_ID,GET_EXERCICE_BY_ID_SOCIETE,GET_EXERCICE_BY_ID,
  GET_CODE_JOURNAUX_BY_ID,GET_CODE_JOURNAUX_BY_EXERCICE,GET_SAISIE_JOURNAL_BY_EXERCICE,GET_SAISIE_JOURNAL_BY_ID,
  GET_JOURNAL_BY_SAISI_JOURNAL,GET_JOURNAL_BY_ID,GET_EXERCICE_ETAT_BY_ID_EXERCICE,GET_EXERCICE_ETAT,
  IS_ALL_EXERCICE_OF_SOCIETE_CLOSE,GET_LAST_RESULTAT}
